name: Coverage

on:
    push:
        branches: [ master ]

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.2'
                    coverage: xdebug

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress

            -   name: Run PHPUnit test suite
                run: ./vendor/bin/phpunit --configuration ./tests/phpunit.xml

            -   name: Update code coverage badge
                uses: timkrase/phpunit-coverage-badge@v1.0.0
                with:
                    report: ./tests/clover.xml
                    report_type: clover
                    coverage_badge_path: ./.github/coverage.svg
                    push_badge: true
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
